### ISSUE TITLE
tg-cli won't recover when a fatal error happens

### ISSUE THREAD

**Issue by Jamesits** [gumblex/tg-export#3]
logs are:

```
2016-10-04 21:40:21,492 [INFO] Exporting messages for *redacted*  from 114600
....115000.........116000.........117000.........118000.........119000.........120000....120400
2016-10-04 21:41:25,170 [INFO] Export to database completed.
2016-10-04 21:42:07,034 [INFO] Getting the remaining 2809549 messages...
2016-10-04 21:42:11,504 [INFO] SIGNAL received
2016-10-04 21:42:11,505 [INFO] S0   telegram-cli                        0x000000010b0a14ba print_backtrace + 42
2016-10-04 21:42:11,506 [INFO] 1   telegram-cli                        0x000000010b0a15b6 termination_signal_handler + 182
2016-10-04 21:42:11,506 [INFO] 2   libsystem_platform.dylib            0x00007fff9f6e7bba _sigtramp + 26
2016-10-04 21:42:11,506 [INFO] 3   telegram-cli                        0x000000010b327bc5 fetch_ds_type_vector + 117
2016-10-04 21:42:11,506 [INFO] 4   telegram-cli                        0x000000010b0b2d23 print_msg_gw + 259
2016-10-04 21:42:11,506 [INFO] 5   telegram-cli                        0x000000010b0edc86 get_messages_on_answer + 886
2016-10-04 21:42:11,506 [INFO] 6   telegram-cli                        0x000000010b0d65f6 tglq_query_result + 1222
2016-10-04 21:42:11,506 [INFO] 7   telegram-cli                        0x000000010b0d3840 work_rpc_result + 208
2016-10-04 21:42:11,506 [INFO] 8   telegram-cli                        0x000000010b0d3124 rpc_execute_answer + 452
2016-10-04 21:42:11,507 [INFO] 9   telegram-cli                        0x000000010b0d2018 process_rpc_message + 2824
2016-10-04 21:42:11,507 [INFO] 10  telegram-cli                        0x000000010b0cf10c rpc_execute + 796
2016-10-04 21:42:11,507 [INFO] 11  telegram-cli                        0x000000010b10b6ce try_rpc_read + 1006
2016-10-04 21:42:11,507 [INFO] 12  telegram-cli                        0x000000010b10b2cc try_read + 572
2016-10-04 21:42:11,507 [INFO] 13  telegram-cli                        0x000000010b10a76a conn_try_read + 106
2016-10-04 21:42:11,507 [INFO] 14  libevent-2.0.5.dylib                0x00000001182a31ba event_base_loop + 1887
2016-10-04 21:42:11,507 [INFO] 15  telegram-cli                        0x000000010b0a23bf net_loop + 159
2016-10-04 21:42:11,507 [INFO] 16  telegram-cli                        0x000000010b0a5474 loop + 788
2016-10-04 21:42:11,507 [INFO] 17  telegram-cli                        0x000000010b0a086d inner_main + 13
2016-10-04 21:42:11,507 [INFO] 18  telegram-cli                        0x000000010b0a1c7f main + 1375
2016-10-04 21:42:11,507 [INFO] 19  libdyld.dylib                       0x00007fff9f4da255 start + 1
2016-10-04 21:42:11,508 [INFO] 20  ???                                 0x0000000000000009 0x0 + 9
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.2_2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/james/code/tg-export/tgcli.py", line 138, in _run_cli
    self.sock.shutdown(socket.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected
```

Then the program stuck there.

**Comment by gumblex** [comment]
Fixed in 0eeaff3.
