### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by KarelWintersky** [gumblex/tg-export#9]
```
python3 export.py -o ./backup -f -p "НРИ: Иллурия - Winterland" -e /usr/local/bin
```
Result:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/root/tg/tg-export/tgcli.py", line 118, in _run_cli
    self.checkproc()
  File "/root/tg/tg-export/tgcli.py", line 109, in checkproc
    preexec_fn=preexec_ignore_sigint if self.ignore_sigint else None)
  File "/usr/lib64/python3.4/subprocess.py", line 856, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.4/subprocess.py", line 1460, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied

```

**Comment by gumblex** [comment]
-e should point to the executable, eg. `-e /usr/local/bin/telegram-cli`
